Taverly dungeon
2011Scape/game pull request #264
Opened 2023-03-24 06:53 UTC by alycii

## What has been done?
- Added all spawns
- Added definitions for hellhounds, monk of zamorak, chaos dwarfs, and the Jailer
- Added dialogue for obtaining the Dusty Key
- Added support for Jail & Dusty Key
- Fixed two critical bugs with doors and walkable tiles

## Has your code been documented?
- Mostly

2023-03-24 12:44 UTC, DesecratedTree commented
pulled to local, did not run into anything major, still a work in progress. approving

2023-03-25 14:35 UTC, skalfate commented
One small typo error in taverley plugin file, line 44 "well" is "wll"

2023-03-25 14:36 UTC, skalfate commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/taverly_dungeon.plugin.kts
> +                        "Wll, this dungeon was quite good to explore ...until I",
typo Wll shoul be well

2023-03-25 14:44 UTC, skalfate requested changes
Looks very well done! Just a small typo away from perfect.

2023-03-27 03:52 UTC, merged