Update pestleAndMortar.plugin.kts
2011Scape/game pull request #291
Opened 2023-03-28 08:19 UTC by raynna

## What has been done?
Fix so you can crush one item with pestle n mortal

2023-03-28 22:27 UTC, Tyluur requested changes

2023-03-28 22:27 UTC, Tyluur commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts
File names should follow the naming convention used throughout the project.

2023-03-28 22:27 UTC, Tyluur commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts
> +            grindItem(player, definitions[source]!!.result, 1)
Is it necessary to use the not-null assertion operator (!!) in this case? 
Or is there a better way you could've written this?

https://kotlinlang.org/docs/null-safety.html#the--operator

2023-03-29 00:35 UTC, alycii reviewed
updated file nime

2023-03-29 00:36 UTC, raynna commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts
I did not make the pestle and mortal, i just applied the fix

2023-03-30 01:00 UTC, merged