WIP: Update netty
2011Scape/game pull request #32
Opened 2023-02-17 12:30 UTC by Paleocene

WIP on updating netty. 

Setting `io.netty.noUnsafe` to true ensures netty keeps using `UnpooledHeapByteBuf`, otherwise it will default to another implementation that doesn't provide access to the `array()` function.

I have commented out `pipeline.remove("login_encoder")` in the `LoginService`. Somehow, in newer versions of netty, a race condition occurs that causes the login encoder to be removed from the pipeline before that pipeline was called. A small Thread.sleep() before removing seems to be functionally the same.

2023-02-24 21:43 UTC, Tyluur commented
Which issues do you have concerns about in 4.1.x?

I didn't experience any in 4.1.44, but 4.1.86 seems to be the most recent and stable version.

2023-02-24 21:55 UTC, Paleocene commented
Using 4.1.86:

![image](https://user-images.githubusercontent.com/123772937/221300441-9ea65066-8f67-45bd-8b28-fab76beb2f0a.png)

Logging in with 4.0.34 works as long as the other changes in this PR are implemented as well

2023-03-15 15:15 UTC, Tyluur requested changes

2023-03-15 15:15 UTC, Tyluur commented on game/build.gradle
What will this property do?

2023-03-15 15:15 UTC, Tyluur commented on game/src/main/kotlin/gg/rsmod/game/protocol/GameHandler.kt
Explain why we want to set the channel to null here - for garbage collection purposes I'm assuming?

2023-03-15 15:15 UTC, Tyluur commented on gradle/properties.gradle
This makes sense.

2023-03-16 13:37 UTC, Paleocene commented on game/src/main/kotlin/gg/rsmod/game/protocol/GameHandler.kt
This is purely a refactor to replace a deprecated function call (`andRemove`) by its functional equivalent (`getAndSet(null)`)

2023-03-16 13:38 UTC, Paleocene commented on game/src/main/kotlin/gg/rsmod/game/service/login/LoginService.kt
This is a hard one for me to wrap my head around. When we leave that line in, a race condition occurs on this (and higher) netty versions, where the login encoder is removed before it can be used, leading to failed logins

2023-04-05 04:30 UTC, alycii commented
Considering this closed

2023-04-05 04:30 UTC, closed without merging