Wilderness NPC and item spawns.
2011Scape/game pull request #332
Opened 2023-04-04 15:41 UTC by HarleyGilpin

Manually added all NPC and item spawns for the wilderness and some wilderness underground dungeon areas.

2023-04-05 04:26 UTC, alycii commented
In the future, please use semantic commit messages. You can find more information on them here:

https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

2023-04-05 04:49 UTC, alycii requested changes

2023-04-05 04:49 UTC, alycii commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10057.plugin.kts
> +spawn_npc(npc = Npcs.LUNDAIL, x = 2535, z = 4719, walkRadius = 0, direction = Direction.SOUTH)
NPCs that don't walk do not need their walkRadius set to 0, simply not having it there will make them stationary. To finish the review, please fix any issues by removing `walkRadius = 0` :)

2023-04-05 14:28 UTC, HarleyGilpin reviewed
Thanks for the feedback, I've fixed the identified issue with NPC walkRadius parameter value being set superfluously.

2023-04-06 07:04 UTC, alycii approved these changes
Quite a lot of data! Nice work 👍

2023-04-06 07:04 UTC, merged