juju and dungeoneering potions and water and herbs and spawns and npc examine text and todo for potions
2011Scape/game pull request #519
Opened 2024-02-16 13:08 UTC by MrSlayerGod

## What has been done?
    • Addition of Juju and Dungeoneering Potions:
        • Implemented compatibility for using Juju vial of water and Dungeoneering water.
    • Herb Additions:
        • Included Dungeoneering herbs and Juju herbs.
    • Legend Guild Basement and Tolna's Rift Spawns:
        • Added spawns in the Legend Guild basement and Tolna's Rift
   • NPC Examine Texts:
        • Included missing examine texts for NPCs to improve immersion and player interaction.
   • TODO for Potions:
        • TODO: Document potion recipes and effects in the game's documentation.

## Has your code been documented? yes

2024-02-17 16:37 UTC, HarleyGilpin requested changes
HerbData enum class needs to be updated to include the required vial item value,

2024-02-17 22:33 UTC, HarleyGilpin commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/CreateUnfinishedPotionAction.kt
Line 51 should return potion.requiredVial

2024-02-17 22:34 UTC, HarleyGilpin requested changes
Please address comment to return potion.requiredVial on line 51 of CreateUnfinishedPotionAction.kt in the canMix function.

2024-02-17 22:43 UTC, MrSlayerGod commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/CreateUnfinishedPotionAction.kt
can show me example what you mean thanks as im half a sleep haha xd been busy all day

2024-02-17 23:27 UTC, HarleyGilpin requested changes

2024-02-17 23:27 UTC, HarleyGilpin commented on game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/mix_potion.plugin.kts
Need to add a check to make sure juju and dungeoneering herbs aren't being used on vials of water.

2024-02-17 23:28 UTC, HarleyGilpin commented
https://github.com/2011Scape/game/assets/75695035/78ee5de8-4c45-4148-a4e1-e0418ad76653

2024-02-19 16:51 UTC, MrSlayerGod commented
https://github.com/2011Scape/game/assets/31116755/78e4e111-3d89-465a-9a84-cd7a0008d223

2025-01-03 21:32 UTC, closed without merging